### ISSUE TITLE
UI: Filtros de busqueda para catalogo de Contratos

### ISSUE THREAD

**Issue by pianodaemon** [pianodaemon/SJO#63]
El usuario requiere poder localizar ciertos contratos con respecto a busquedas parametrizables. Una vez que los resultados se generen en el backend, estos deberan de ser paginables mediante el uso de un end point que asi lo permita (Asi se evitara la comunicacion interprocesos de grandes tramas de bytes).

**Comment by neftali-lopez** [comment]
Hola. Este requerimiento por su naturaleza es un reporte.
1. En el módulo CRUD de Contratos ya se cuenta con algunas opciones de búsqueda en el DataTable.
2. Para algo más completo, lo correcto es construir un reporte.

**Comment by pianodaemon** [comment]
Aun son requeridos los filtros por rango de Fechas.
